#!/bin/bash

##===========================================================================================================================
##
##         FILE: cronexperms
##
##  DESCRIPTION: This is the experms-script for cron. It checkes if Experms is running. If not it starts it.
##
##        NOTES: You can let cron run this script (e.g. every 5 minutes) in order to make sure Experms is running permanentely.
##               Example for crontab:
##               */5 * * * * /usr/bin/cronexperms
##
##===========================================================================================================================


if ! ps -Ao fname | egrep -q experms
then
    experms start
fi
exit 0

